name: Init Project

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: create

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.ref == 'refs/heads/master'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Git Commit/Push Changes
        uses: actions/checkout@v2

      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Substitute placeholders
        run: |
          sed -i "s/<PACKAGE-ID>/${{ github.event.repository.name }}/g" README.md
          name=$(echo ${{ github.event.repository.name }} | sed -e "s/-_/ /g" -e "s/\b\(.\)/\u\1/g")
          sed -i "s/<PACKAGE-NAME>/$name/g" README.md
          git rm .github/workflows/init.yml

      - name: Git Commit/Push Changes
        uses: actions-x/commit@v1
